language: python
python:
- "2.7"
# command to install dependencies
sudo: required
install: "pip install -r requirements.txt"
before_script:
    - "createdb books"
    - "psql books < books.sql"
# command to run tests
script: python tests.py