language: python
python:
- "2.7"
# command to install dependencies
sudo: required
install: "pip install -r requirements.txt"
before_script:
    - "createdb plants"
    - "psql ratings < ratings.sql"
# command to run tests
script: python tests.py